name: Cloud PC

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install Desktop
        run: |
          sudo apt update
          sudo apt install xfce4 xfce4-goodies -y

      - name: Keep Server Running
        run: |
          echo "Cloud PC running"
          sleep 21600
